package desktopremotecontrollerpc;

import java.util.logging.Level;
import java.util.logging.Logger;

public class GUI extends javax.swing.JFrame {

    public static AppConnection connect = new AppConnection();
    
    public GUI() {
        initComponents();
        machineIpLabel.setText(connect.getIpAddress());
        currentPortLabel.setText("3000");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        currentStateLabel = new javax.swing.JLabel();
        ipLabel = new javax.swing.JLabel();
        machineIpLabel = new javax.swing.JLabel();
        portLabel = new javax.swing.JLabel();
        currentPortLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        currentStateLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        currentStateLabel.setText("Current State Label");

        ipLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ipLabel.setText("IP:");

        machineIpLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        machineIpLabel.setText("This Machine IP");

        portLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        portLabel.setText("Port:");

        currentPortLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        currentPortLabel.setText("Current Port");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ipLabel)
                        .addGap(18, 18, 18)
                        .addComponent(machineIpLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(currentStateLabel)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(portLabel)
                            .addGap(18, 18, 18)
                            .addComponent(currentPortLabel))))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipLabel)
                    .addComponent(machineIpLabel))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portLabel)
                    .addComponent(currentPortLabel))
                .addGap(33, 33, 33)
                .addComponent(currentStateLabel)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
        
            connect.startServer(3000);
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentPortLabel;
    private static javax.swing.JLabel currentStateLabel;
    private javax.swing.JLabel ipLabel;
    private javax.swing.JLabel machineIpLabel;
    private javax.swing.JLabel portLabel;
    // End of variables declaration//GEN-END:variables
}
